[package]
name = "rustnewsletter"
version = "0.1.0"
edition = "2021"
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rustnewsletter"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
actix-web = "4"

[dev-dependencies]
reqwest = "0.11"
